// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.API.Data;

#nullable disable

namespace Products.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502201159_mysqlMigrations")]
    partial class mysqlMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Products.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "42'' TV",
                            Name = "TV"
                        },
                        new
                        {
                            Id = 2,
                            Description = "8KG fridge",
                            Name = "Fridge"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Xiaomi",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iphone",
                            Name = "Smartphone"
                        });
                });

            modelBuilder.Entity("Products.API.Models.ProductSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ProductSeller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 1599.00m,
                            ProductId = 1,
                            SellerId = 1,
                            Sku = "faaef8a4-dc31-49a2-b8d8-3f8bb8134e10",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Price = 3499.00m,
                            ProductId = 1,
                            SellerId = 2,
                            Sku = "e58acd35-422c-4048-afcb-437eb12c73fb",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Price = 3999.00m,
                            ProductId = 1,
                            SellerId = 1,
                            Sku = "347e9fcf-57fd-4e06-bffb-4a06901b8e46",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Price = 3999.00m,
                            ProductId = 2,
                            SellerId = 3,
                            Sku = "e0973591-e5e0-475a-b50b-3326bb3088b9",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Price = 3999.00m,
                            ProductId = 3,
                            SellerId = 2,
                            Sku = "a7479672-91ba-4c3f-ba49-31d1932f1c6d",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Price = 3999.00m,
                            ProductId = 4,
                            SellerId = 3,
                            Sku = "37d2055f-6839-467c-8b6e-a740ad081019",
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("Products.API.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tech store"
                        },
                        new
                        {
                            Id = 2,
                            Name = "House store"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Big Market"
                        });
                });

            modelBuilder.Entity("Products.API.Models.ProductSeller", b =>
                {
                    b.HasOne("Products.API.Models.Product", "Product")
                        .WithMany("ProductSellers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products.API.Models.Seller", "Seller")
                        .WithMany("ProductSellers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Products.API.Models.Product", b =>
                {
                    b.Navigation("ProductSellers");
                });

            modelBuilder.Entity("Products.API.Models.Seller", b =>
                {
                    b.Navigation("ProductSellers");
                });
#pragma warning restore 612, 618
        }
    }
}
