// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.API.Data;

#nullable disable

namespace Products.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Products.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "42'' TV",
                            Name = "TV"
                        },
                        new
                        {
                            Id = 2,
                            Description = "8KG fridge",
                            Name = "Fridge"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Xiaomi",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iphone",
                            Name = "Smartphone"
                        });
                });

            modelBuilder.Entity("Products.API.Models.ProductSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ProductSeller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 1599.00m,
                            ProductId = 1,
                            SellerId = 1,
                            Sku = "152c048a-8f53-45fb-b080-891bf012d9b7",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Price = 3499.00m,
                            ProductId = 1,
                            SellerId = 2,
                            Sku = "32ea5a56-e466-455c-97f3-4847aac56aa5",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Price = 3999.00m,
                            ProductId = 1,
                            SellerId = 1,
                            Sku = "bb216151-4fba-4fb2-b99e-d7c2f2b43646",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Price = 3999.00m,
                            ProductId = 2,
                            SellerId = 3,
                            Sku = "cbd9b9d2-2351-4c22-ab08-dd1d8548e0a0",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Price = 3999.00m,
                            ProductId = 3,
                            SellerId = 2,
                            Sku = "8509dea8-7067-4243-afb2-6135358a0487",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Price = 3999.00m,
                            ProductId = 4,
                            SellerId = 3,
                            Sku = "0d11bac6-be52-4046-8607-be9eba10d97c",
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("Products.API.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tech store"
                        },
                        new
                        {
                            Id = 2,
                            Name = "House store"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Big Market"
                        });
                });

            modelBuilder.Entity("Products.API.Models.ProductSeller", b =>
                {
                    b.HasOne("Products.API.Models.Product", "Product")
                        .WithMany("ProductSellers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products.API.Models.Seller", "Seller")
                        .WithMany("ProductSellers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Products.API.Models.Product", b =>
                {
                    b.Navigation("ProductSellers");
                });

            modelBuilder.Entity("Products.API.Models.Seller", b =>
                {
                    b.Navigation("ProductSellers");
                });
#pragma warning restore 612, 618
        }
    }
}
